# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Depctl < Formula
  desc "Manage project development dependencies"
  homepage "https://github.com/twelvelabs/depctl"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.2/depctl_0.1.2_darwin_arm64.tar.gz"
      sha256 "ae8d6da79017796f182e1ef94c52b1fde952def7c2d2537b12d6c0e140b7cb0e"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.2/depctl_0.1.2_darwin_amd64.tar.gz"
      sha256 "2dbe608ca560b76e5be92e89a75ee93e166628c6c17c296cade585e92911cc44"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.2/depctl_0.1.2_linux_arm64.tar.gz"
      sha256 "4c219433fc3047bf1190b309f581ef562c7156fb524ceefe0f7ec43d73b89885"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.2/depctl_0.1.2_linux_amd64.tar.gz"
      sha256 "e3088c7c5aa76f6fa3040e9e8b61ba9353f865503060c45def7804af469ce75c"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
  end

  test do
    system "#{bin}/depctl --version"
  end
end
