# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Depctl < Formula
  desc "Manage project development dependencies"
  homepage "https://github.com/twelvelabs/depctl"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.1/depctl_0.1.1_darwin_arm64.tar.gz"
      sha256 "6f6f2e59f3d06d775d1045d704ea2e745b5d13c7e5f4b293571f463f8b2251f1"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.1/depctl_0.1.1_darwin_amd64.tar.gz"
      sha256 "14bf2e8b20f238e9a2416037eef1931684fe9e3ca36c3876f8ca4bd44fff0044"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.1/depctl_0.1.1_linux_arm64.tar.gz"
      sha256 "dcf0b728c975f4b2f2da014ee655af6889fe03b34c0fe82270047c34a43a18e2"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/depctl/releases/download/v0.1.1/depctl_0.1.1_linux_amd64.tar.gz"
      sha256 "899b9c339e50e36cdb1171a6d5bebde28d6d089990e73495ed63ff6e5249503e"

      def install
        bin.install "depctl"
        bash_completion.install "completions/depctl.bash" => "depctl"
        zsh_completion.install "completions/depctl.zsh" => "_depctl"
        fish_completion.install "completions/depctl.fish"
        man1.install "manpages/depctl.1.gz"
      end
    end
  end

  test do
    system "#{bin}/depctl --version"
  end
end
