# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envctl < Formula
  desc "Manage project environment variables"
  homepage "https://github.com/twelvelabs/envctl"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.1/envctl_0.4.1_darwin_amd64.tar.gz"
      sha256 "b3539916414604220b863edb62c87c6facecfe0ffa1f049b94e30a49729b937a"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.1/envctl_0.4.1_darwin_arm64.tar.gz"
      sha256 "ef7da06b248ee07a4345304e9ad38ffe44609ab522103663245f7de7cf260d18"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.1/envctl_0.4.1_linux_amd64.tar.gz"
      sha256 "ff719c931d42d0af491bdd6a87097b75703bfc435863e4a413e039568c7800ef"
      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.1/envctl_0.4.1_linux_arm64.tar.gz"
      sha256 "7250cd62724a0d07fb60cfdfdef442fa1738c8ad8c22763349175e5aec886101"
      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
  end

  test do
    system "#{bin}/envctl --version"
  end
end
