# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envctl < Formula
  desc "Manage project environment variables"
  homepage "https://github.com/twelvelabs/envctl"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.0/envctl_0.4.0_darwin_amd64.tar.gz"
      sha256 "85a8ea38774ee9444486a4b682db23865a166a9b0c3f549d57df8542faaa6e3f"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.0/envctl_0.4.0_darwin_arm64.tar.gz"
      sha256 "f01a1586df1016b4ed05d6930e27380307f6797e0a8c3251ecc82bdcdcd37172"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.0/envctl_0.4.0_linux_amd64.tar.gz"
      sha256 "b231ec1cf853c275c45099cee0be5fe8d3f612a2565731710fbbede9fcc5bfe2"
      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.4.0/envctl_0.4.0_linux_arm64.tar.gz"
      sha256 "c726e16fb67e3c40ca93dbb95033bef7bdb6c69787b1bca21b03710518317126"
      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
  end

  test do
    system "#{bin}/envctl --version"
  end
end
