# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envctl < Formula
  desc "Manage project environment variables"
  homepage "https://github.com/twelvelabs/envctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.1.0/envctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "bcad5aa08409e9787fdf7150340a66afd74189ab2f301293978b654ce6c9efd0"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.1.0/envctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "8842f3e3602e30f03e39c10d34f6fea8169863d43b641b77083adbdf9f893ff5"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.1.0/envctl_0.1.0_linux_arm64.tar.gz"
      sha256 "a07aa69a083fea8c7482378cf6d8ec7ccb11bb3ea76f7b170b42376d748230eb"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/envctl/releases/download/v0.1.0/envctl_0.1.0_linux_amd64.tar.gz"
      sha256 "4af1c26ad85c1dafac61b69cafcaddc0e967ffef0e4114e273dd7fd7f8f9c05a"

      def install
        bin.install "envctl"
        bash_completion.install "completions/envctl.bash" => "envctl"
        zsh_completion.install "completions/envctl.zsh" => "_envctl"
        fish_completion.install "completions/envctl.fish"
        man1.install "manpages/envctl.1.gz"
      end
    end
  end

  test do
    system "#{bin}/envctl -v"
  end
end
