# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemadoc < Formula
  desc "Generate markdown documents from JSON schema files"
  homepage "https://github.com/twelvelabs/schemadoc"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.3.0/schemadoc_0.3.0_darwin_arm64.tar.gz"
      sha256 "0ce236c22909c2580bc5291ad8d63ac63dfd4d270afeafa606710a2b2c9deb2d"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.3.0/schemadoc_0.3.0_darwin_amd64.tar.gz"
      sha256 "104f65bb585a8b0aae6a32776a040e95dcb3fe31e5cb5085bd1be376c0adefcd"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.3.0/schemadoc_0.3.0_linux_arm64.tar.gz"
      sha256 "0b10abcfded53cf4c18885a63064064fc827270e36fbabec018a629a6ca8afcc"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.3.0/schemadoc_0.3.0_linux_amd64.tar.gz"
      sha256 "34b15467f568fe56997b3a262c08d124765becef12a506f6f251cff92c8c7f99"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
  end

  test do
    system "#{bin}/schemadoc --version"
  end
end
