# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemadoc < Formula
  desc "Generate markdown documents from JSON schema files"
  homepage "https://github.com/twelvelabs/schemadoc"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.4.0/schemadoc_0.4.0_darwin_arm64.tar.gz"
      sha256 "6575f31d55586443bb95d6169c1347f0d2fb25649008bcb4dbef2ec39c118727"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.4.0/schemadoc_0.4.0_darwin_amd64.tar.gz"
      sha256 "3f82c72d428d367ee88453845859523f19cb2d67087509b9c713f819ddec426c"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.4.0/schemadoc_0.4.0_linux_arm64.tar.gz"
      sha256 "237748131f2c381a4634b49486e9695e1016596e8ed386c6eec802519754c4ea"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.4.0/schemadoc_0.4.0_linux_amd64.tar.gz"
      sha256 "567d1ceb689ff16071d8d18ebcfe226729a84939f19a2ff8c34009a8aec93b24"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
  end

  test do
    system "#{bin}/schemadoc --version"
  end
end
