# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemadoc < Formula
  desc "Generate markdown documents from JSON schema files"
  homepage "https://github.com/twelvelabs/schemadoc"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.5.0/schemadoc_0.5.0_darwin_arm64.tar.gz"
      sha256 "8ab60b4605f3bf80ee8bb217dd494e59578ba1c91aa34499fb6a23380e3b8870"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.5.0/schemadoc_0.5.0_darwin_amd64.tar.gz"
      sha256 "0810111ff873d1d83cacb0d2cac4433420dc1433031bcbf814beed4c7174c543"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.5.0/schemadoc_0.5.0_linux_arm64.tar.gz"
      sha256 "ef0912f269f5d9a7885998262fa9d9c45c13c3a8e7f9f4e09c05b2927e6c6bb3"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/schemadoc/releases/download/v0.5.0/schemadoc_0.5.0_linux_amd64.tar.gz"
      sha256 "6005c227cba73c7de69ba98e446cf6d9a09da7066dfd431de735f536d47f1908"

      def install
        bin.install "schemadoc"
        bash_completion.install "completions/schemadoc.bash" => "schemadoc"
        zsh_completion.install "completions/schemadoc.zsh" => "_schemadoc"
        fish_completion.install "completions/schemadoc.fish"
        man1.install "manpages/schemadoc.1.gz"
      end
    end
  end

  test do
    system "#{bin}/schemadoc --version"
  end
end
