# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stamp < Formula
  desc "A project and file scaffolding tool"
  homepage "https://github.com/twelvelabs/stamp"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.4.2/stamp_0.4.2_darwin_arm64.tar.gz"
      sha256 "5fdcd83294878b419853923bdd4cdeea61cceaf4cc4462628205e26a6da2f2c0"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.4.2/stamp_0.4.2_darwin_amd64.tar.gz"
      sha256 "f8785c30b1976bb5ef5b2cc35ffea5b5e31b8d377e556b4516c1c7f56b9e41a6"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.4.2/stamp_0.4.2_linux_amd64.tar.gz"
      sha256 "5f0f9c20d3af76ad4c754687128eb5f084352fe8cfb0bf38bde47c72d7090907"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.4.2/stamp_0.4.2_linux_arm64.tar.gz"
      sha256 "02ad1b8793377873a27964d6604c1a50901bfbb4f56c34346791a3302cda6c5d"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
  end

  test do
    system "#{bin}/stamp --version"
  end
end
