# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stamp < Formula
  desc "A project and file scaffolding tool"
  homepage "https://github.com/twelvelabs/stamp"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.5.1/stamp_0.5.1_darwin_amd64.tar.gz"
      sha256 "d8ab1516d1d76691ffc0ec26e2a838d68dd6765987c344d716d1fc0b0fe4ab0d"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.5.1/stamp_0.5.1_darwin_arm64.tar.gz"
      sha256 "abff1971a76f7ea315741620441f287b269a3d632225fa1da2ed13f07e2f32e8"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.5.1/stamp_0.5.1_linux_arm64.tar.gz"
      sha256 "344e730eac895777d9e310cc85da759a86f06b39fe44b3dfb7f3899513d77d7c"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.5.1/stamp_0.5.1_linux_amd64.tar.gz"
      sha256 "55e267e10322ff71e058d2f4c23c0ab9421f430dc77a66316d8dc5ffea6662cc"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
  end

  test do
    system "#{bin}/stamp --version"
  end
end
