# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stamp < Formula
  desc "A project and file scaffolding tool"
  homepage "https://github.com/twelvelabs/stamp"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.7.2/stamp_0.7.2_darwin_amd64.tar.gz"
      sha256 "0093c10010236c9fa9ea864e28a8f92971de5275e8d4cc85ecc5eb06aa419a8d"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.7.2/stamp_0.7.2_darwin_arm64.tar.gz"
      sha256 "fc89e3aa7b4690c19ecb0e3230e06fedffccbee7bc231a0d6b7dea5bd4c039c1"

      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.7.2/stamp_0.7.2_linux_amd64.tar.gz"
      sha256 "9478787459dd8ff3814bda0bd5976ef1fb091494e10030644b0adeb15ac050e6"
      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/stamp/releases/download/v0.7.2/stamp_0.7.2_linux_arm64.tar.gz"
      sha256 "0a97d81b7c3e17ee887590f68b9136163cfd9f7ee09c31414c091b9adf8ec1b1"
      def install
        bin.install "stamp"
        bash_completion.install "completions/stamp.bash" => "stamp"
        zsh_completion.install "completions/stamp.zsh" => "_stamp"
        fish_completion.install "completions/stamp.fish"
        man1.install "manpages/stamp.1.gz"
      end
    end
  end

  test do
    system "#{bin}/stamp --version"
  end
end
