# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stylist < Formula
  desc "Manage all your code quality tools with a single executable"
  homepage "https://github.com/twelvelabs/stylist"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twelvelabs/stylist/releases/download/v0.2.0/stylist_0.2.0_darwin_arm64"
      sha256 "5c78b2132a43e159050f6160fae90057fa852d93157eb915dd8fc74bf9087b82"

      def install
        bin.install "stylist_0.2.0_darwin_arm64" => "stylist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/stylist/releases/download/v0.2.0/stylist_0.2.0_darwin_amd64"
      sha256 "cf79a2c6d138d02d579341864bb730bf5fc5d0cf54fde147299c88d5004a4c35"

      def install
        bin.install "stylist_0.2.0_darwin_amd64" => "stylist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/twelvelabs/stylist/releases/download/v0.2.0/stylist_0.2.0_linux_amd64"
      sha256 "bcba9cb3209dc3c7fc929f06247d81eb4738551c5938e17179af8e52e9c94b4a"

      def install
        bin.install "stylist_0.2.0_linux_amd64" => "stylist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvelabs/stylist/releases/download/v0.2.0/stylist_0.2.0_linux_arm64"
      sha256 "892b3cec429024198ea212f3c60cb10a38b712058f573d8f9907a7495a085dd2"

      def install
        bin.install "stylist_0.2.0_linux_arm64" => "stylist"
      end
    end
  end
end
